[build]
  # Default build command.
  command = "cd ./data_importer/; npm install; npm run build; cd ../pantry-ui/; npm install; npm run build"
  publish = "pantry-ui/build/"


[[redirects]]
  from = "/*"
  to = "/index.html?pipeline=:splat"
  status = 200
